import {
  ChevronRightSquare,
  Github,
  Hand,
  ListMinus,
  Loader2,
  LogIn,
  LogOut,
  Menu,
  Merge,
  Presentation,
  Trash2,
  UserX2,
  XSquare,
} from 'lucide-react';

export const Icons = {
  loader: Loader2,
  login: LogIn,
  work: ChevronRightSquare,
  help: Hand,
  ready: Presentation,
  logout: LogOut,
  popQueue: ListMinus,
  clearQueue: XSquare,
  purge: Trash2,
  mergeRoom: Merge,
  removeUser: UserX2,
  menu: Menu,
  gitHub: Github,
};
